### ISSUE TITLE
Kotlin + Groovy cross compilation doesn't work

### ISSUE THREAD

**Issue by RaviH** [nebula-plugins/gradle-java-cross-compile-plugin#1]
Hello,

I am attaching a sample project. It doesn't seem like I can mix Groovy and Kotlin code. Groovy using Kotlin works w/o your plugin, and so does Kotlin using Groovy but I was hoping to have interdependencies with your plugin. Not in scope of your plugin?

Thank you,
Ravi Hasija

[kotlin-groovy.zip](https://github.com/nebula-plugins/gradle-java-cross-compile-plugin/files/1389937/kotlin-groovy.zip)

**Comment by Vampire** [comment]
No, this plugin is about setting the bootpath when compiling code that targets e. g. Java 8 while Gradle is running on Java 9. If the path is not set, you can compile successfully, while actually using Java 9 API and it will only fail at runtime. This plugin searches for the right boot path and sets it accordingly or errors out.

**Comment by RaviH** [comment]
Thank you for your reply and explanation!
